configuration:
  template_dir:
    - "git://github.com/moremoban/pypi-mobans.git?branch=dev&submodule=true!/templates"
    - "git://github.com/moremoban/pypi-mobans.git?branch=dev&submodule=true!/statics"
    - ".moban.d"
  configuration: "pypi-mobans-pkg.yml"
targets:
  - "README.rst": CUSTOM_README.rst.jj2
  - "LICENSE": newbsd_license.jj2
  - "setup.py": custom_setup.py.jj2
  - "requirements.txt": requirements.txt.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - "test.sh": test.script.jj2
  - "pypi_mobans_pkg/_version.py": "_version.py.jj2"
  - .gitignore: gitignore.jj2
  - .travis.yml: custom_travis.yml.jj2
  - output: "CHANGELOG.rst"
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
