requires:
  - type: git
    url: https://github.com/moremoban/pypi-mobans
    submodule: true
configuration:
  template_dir:
  - ".moban.d"
  - "pypi-mobans:templates"
  configuration: "pypi-mobans-pkg.yml"
targets:
  - "README.rst": CUSTOM_README.rst.jj2
  - "LICENSE": NEW_BSD_LICENSE.jj2
  - "setup.py": custom_setup.py.jj2
  - "requirements.txt": requirements.txt.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - "test.sh": test.script.jj2
  - "pypi_mobans_pkg/_version.py": "_version.py.jj2"
  - .gitignore: gitignore.jj2
  - .travis.yml: travis.yml.jj2
  - output: "CHANGELOG.rst"
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
